/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dona.stm.gui;

import javax.swing.JFrame;

/**
 *
 * @author Cveti
 */
public class MenuJPanel extends javax.swing.JPanel {

    //parent
    private final CardLayoutCallback frame;

    /**
     * Creates new form NewJPanel
     */
    public MenuJPanel(StorageManagementJFrame frame) {
        super();
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assortmentsJButton1 = new javax.swing.JButton();
        contractorsJButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        assortmentsJButton1.setText("Assortments");
        assortmentsJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assortmentsJButton1ActionPerformed(evt);
            }
        });

        contractorsJButton1.setText("Contractors");
        contractorsJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractorsJButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(assortmentsJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contractorsJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(assortmentsJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contractorsJButton1)
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assortmentsJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assortmentsJButton1ActionPerformed
        frame.getCardLayout().show(frame.getCardJPanel(), CLJPanelName.Assortment.toString());
    }//GEN-LAST:event_assortmentsJButton1ActionPerformed

    private void contractorsJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractorsJButton1ActionPerformed
        frame.getCardLayout().show(frame.getCardJPanel(), CLJPanelName.Contractors.toString());
    }//GEN-LAST:event_contractorsJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assortmentsJButton1;
    private javax.swing.JButton contractorsJButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
