/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dona.stm.gui;

import static com.dona.stm.gui.CLJPanelName.Contractors;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author Konstantin Tsanov <k.tsanov@gmail.com>
 */
public class StorageManagementJFrame extends javax.swing.JFrame implements CardLayoutCallback {

    private JPanel cardJPanel;
    private ContractorsJPanel contractorsJPanel;
    private AddProductJPanel assortmentsAddingJPanel;
    private final CardLayout cardLayout = new CardLayout();
    private MenuJPanel optionsJPanel;

    /**
     * Creates new form NewJFrame
     */
    public StorageManagementJFrame() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        createMenuBar();
        optionsJPanel = new MenuJPanel(this);
        cardJPanel = new JPanel();
        contractorsJPanel = new ContractorsJPanel();
        assortmentsAddingJPanel = new AddProductJPanel();
        cardJPanel.setLayout(cardLayout);
        cardJPanel.add(assortmentsAddingJPanel, CLJPanelName.Assortment.toString());
        cardJPanel.add(contractorsJPanel, CLJPanelName.Contractors.toString());
        add(optionsJPanel, BorderLayout.WEST);
        add(cardJPanel, BorderLayout.EAST);
        pack();
    }

    private void setLanguage(String language, String country) {
        assortmentsAddingJPanel.SetComponentText(language, country);
    }

    private void createMenuBar() {
        JMenuBar menubar = new JMenuBar();
        JMenu file = new JMenu("File");
        file.setMnemonic(KeyEvent.VK_F);
        JMenuItem eMenuItem = new JMenuItem("Exit");
        eMenuItem.setMnemonic(KeyEvent.VK_E);
        eMenuItem.setToolTipText("Exit application");
        eMenuItem.addActionListener((ActionEvent event) -> {
            System.exit(0);
        });
        file.add(eMenuItem);
        menubar.add(file);

        JMenu options = new JMenu("Options");
        file.setMnemonic(KeyEvent.VK_O);
        JMenu language = new JMenu("Language");
        JMenuItem english = new JMenuItem("English");
        english.addActionListener((ActionEvent event) -> {
            setLanguage("en", "US");
        });
        JMenuItem bulgarian = new JMenuItem("Български");
        bulgarian.addActionListener((ActionEvent event) -> {
            setLanguage("bg", "BG");
        });
        language.add(english);
        language.add(bulgarian);
        options.add(language);
        menubar.add(options);
        setJMenuBar(menubar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StorageManagementJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StorageManagementJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StorageManagementJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StorageManagementJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StorageManagementJFrame frame = new StorageManagementJFrame();
                frame.setVisible(true);
            }
        });
    }

    @Override
    public JPanel getCardJPanel() {
        return cardJPanel;
    }

    @Override
    public CardLayout getCardLayout() {
        return cardLayout;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
